[package]
name = "advent2022"
version = "0.1.0"
edition = "2021"

default-run = "2"

[dependencies]
derivative = "2.2.0"
num-bigint = "0.4.4"
num-traits = "0.2.17"
pathfinding = "4.4.0"
regex = "1.10.2"
